### ISSUE TITLE
怎么联系你，正在做merlinclash的界面

### ISSUE THREAD

**Issue by ccssyybb** [ZiGmaX809/Clash-For-Merlin#2]
测试了在机子上，会出现只能上tg不能上外网的问题，

**Comment by ZiGmaX809** [comment]
直接在这里讨论就行了

贴一下『设备』『版本』『iptable』『设备ip、dns等』『clash日志』

**Comment by ccssyybb** [comment]
> 直接在这里讨论就行了
> 
> 贴一下『设备』『版本』『iptable』『设备ip、dns等』『clash日志』

AX88U，clashR核心，iptables写入udp转发部分，网络直接卡死，只能重启。
除了没有写fake-ip那两句

**Comment by ccssyybb** [comment]
> 直接在这里讨论就行了
> 
> 贴一下『设备』『版本』『iptable』『设备ip、dns等』『clash日志』

直接将你的tcp udp iptables复制使用了。还是老样子。一写入upd的iptables，就断网，路由无法访问。所以无法查看日志发生什么事。
有TG号吗，发我弄好的梅林UI包给你看下。或者有在梅林的TG群没

**Comment by ZiGmaX809** [comment]
ZiGmaX809
我在ks群，上面是我的id

**Comment by vj23456** [comment]
围观大佬间的对话，坐等新版本

**Comment by wolfccb** [comment]
小白求一个能在koolshare软件中心用的clash插件……

**Comment by ZiGmaX809** [comment]
> 小白求一个能在koolshare软件中心用的clash插件……

你联系上面的大佬，他在做

**Comment by flyhigherpi** [comment]
> 小白求一个能在koolshare软件中心用的clash插件……

还有没进电报群的漏网之鱼？
